# Generated by Django 4.1.2 on 2022-10-18 14:05

import bulk_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabasesBulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_ResearchGroup', models.FileField(blank=True, null=True, upload_to='', verbose_name='Research groups')),
                ('bulk_Professor', models.FileField(blank=True, null=True, upload_to='', verbose_name='Professors')),
                ('bulk_Patent', models.FileField(blank=True, null=True, upload_to='', verbose_name='Patents')),
            ],
            options={
                'verbose_name': 'Update databases with CSV dataset',
            },
            bases=(bulk_data.models.Bulker, models.Model),
        ),
    ]
