# Generated by Django 4.1 on 2022-08-30 23:12

import bulk_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfessorBulk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="", verbose_name="File")),
            ],
            options={
                "verbose_name": "Update Professors database",
            },
            bases=(models.Model, bulk_data.models.Bulker),
        ),
    ]
