# Generated by Django 3.2.15 on 2022-09-15 18:20

import bulk_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentsBulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Update Patents database',
            },
            bases=(bulk_data.models.Bulker, models.Model),
        ),
    ]
