# Generated by Django 3.2.15 on 2022-09-15 19:23

import bulk_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_data', '0002_patentsbulk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabasesBulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_ResearchGroup', models.FileField(upload_to='', verbose_name='Research groups')),
                ('bulk_Professor', models.FileField(upload_to='', verbose_name='Professors')),
                ('bulk_Patent', models.FileField(upload_to='', verbose_name='Patents')),
            ],
            options={
                'verbose_name': 'Update Patents database',
            },
            bases=(bulk_data.models.Bulker, models.Model),
        ),
        migrations.DeleteModel(
            name='GroupsBulk',
        ),
        migrations.DeleteModel(
            name='PatentsBulk',
        ),
        migrations.DeleteModel(
            name='ProfessorBulk',
        ),
    ]
