# Generated by Django 4.1 on 2022-08-29 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="ProfessorModel",
            fields=[
                (
                    "personbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="researchers.personbase",
                    ),
                ),
                (
                    "ID",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("faculty_0001", "Facultad de administración"),
                            (
                                "faculty_0002",
                                "Facultad de ciencias exactas y naturales",
                            ),
                            ("faculty_0003", "Facultad de ingeniería y arquitectura"),
                            (
                                "faculty_0004",
                                "Instituto de estudios ambientales - idea - manizales",
                            ),
                        ],
                        max_length=12,
                        verbose_name="faculty",
                    ),
                ),
                (
                    "departament",
                    models.CharField(
                        choices=[
                            ("departament_0001", "Departamento de administración"),
                            ("departament_0002", "Departamento de ciencias humanas"),
                            ("departament_0003", "Departamento de física y química"),
                            (
                                "departament_0004",
                                "Departamento de informática y computación",
                            ),
                            ("departament_0005", "Departamento de ingeniería civil"),
                            (
                                "departament_0006",
                                "Departamento de ingeniería eléctrica, electrónica y computación",
                            ),
                            (
                                "departament_0007",
                                "Departamento de ingeniería industrial",
                            ),
                            ("departament_0008", "Departamento de ingeniería química"),
                            ("departament_0009", "Departamento de matemáticas"),
                            ("departament_0010", "Escuela de arquitectura y urbanismo"),
                            (
                                "departament_0011",
                                "Instituto de estudios ambientales - idea - manizales",
                            ),
                        ],
                        max_length=16,
                        verbose_name="departament",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("researcher_category_0001", "Investigador asociado"),
                            ("researcher_category_0002", "Investigador emerito"),
                            ("researcher_category_0003", "Investigador junior"),
                            ("researcher_category_0004", "Investigador senior"),
                            ("researcher_category_0005", "Sin información"),
                        ],
                        max_length=24,
                        verbose_name="category",
                    ),
                ),
            ],
            bases=("researchers.personbase",),
        ),
    ]
