# Generated by Django 3.2.15 on 2022-09-19 00:34

from django.db import migrations, models
import researchers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('professor_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Professor ID')),
                ('category', models.CharField(choices=[('researcher_category_0001', 'Investigador asociado'), ('researcher_category_0002', 'Investigador emerito'), ('researcher_category_0003', 'Investigador junior'), ('researcher_category_0004', 'Investigador senior'), ('researcher_category_0005', 'Sin información')], max_length=24, verbose_name='Category')),
                ('faculty', models.CharField(choices=[('faculty_0001', 'Facultad de administración'), ('faculty_0002', 'Facultad de ciencias exactas y naturales'), ('faculty_0003', 'Facultad de ingeniería y arquitectura'), ('faculty_0004', 'Instituto de estudios ambientales - idea - manizales')], max_length=12, verbose_name='Faculty')),
                ('departament', models.CharField(choices=[('departament_0001', 'Departamento de administración'), ('departament_0002', 'Departamento de ciencias humanas'), ('departament_0003', 'Departamento de física y química'), ('departament_0004', 'Departamento de informática y computación'), ('departament_0005', 'Departamento de ingeniería civil'), ('departament_0006', 'Departamento de ingeniería eléctrica, electrónica y computación'), ('departament_0007', 'Departamento de ingeniería industrial'), ('departament_0008', 'Departamento de ingeniería química'), ('departament_0009', 'Departamento de matemáticas'), ('departament_0010', 'Escuela de arquitectura y urbanismo'), ('departament_0011', 'Instituto de estudios ambientales - idea - manizales')], max_length=16, verbose_name='Departament')),
            ],
            options={
                'verbose_name': 'Professor',
            },
            bases=(researchers.models.PersonBase, models.Model),
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('researcher_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Researcher ID')),
                ('joined', models.DateField(default='django.utils.timezone.now', verbose_name='Join')),
                ('departed', models.DateField(blank=True, null=True, verbose_name='Departed')),
            ],
            options={
                'verbose_name': 'Researcher',
            },
            bases=(researchers.models.PersonBase, models.Model),
        ),
    ]
