# Generated by Django 3.2.15 on 2022-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='category',
            field=models.CharField(choices=[('researcher_category_0001', 'Investigador asociado'), ('researcher_category_0002', 'Investigador emerito'), ('researcher_category_0003', 'Investigador junior'), ('researcher_category_0004', 'Investigador senior'), ('researcher_category_0005', 'Sin información')], max_length=124, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='departament',
            field=models.CharField(choices=[('departament_0001', 'Departamento de administración'), ('departament_0002', 'Departamento de ciencias humanas'), ('departament_0003', 'Departamento de física y química'), ('departament_0004', 'Departamento de informática y computación'), ('departament_0005', 'Departamento de ingeniería civil'), ('departament_0006', 'Departamento de ingeniería eléctrica, electrónica y computación'), ('departament_0007', 'Departamento de ingeniería industrial'), ('departament_0008', 'Departamento de ingeniería química'), ('departament_0009', 'Departamento de matemáticas'), ('departament_0010', 'Escuela de arquitectura y urbanismo'), ('departament_0011', 'Instituto de estudios ambientales - idea - manizales')], max_length=116, verbose_name='Departament'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='faculty',
            field=models.CharField(choices=[('faculty_0001', 'Facultad de administración'), ('faculty_0002', 'Facultad de ciencias exactas y naturales'), ('faculty_0003', 'Facultad de ingeniería y arquitectura'), ('faculty_0004', 'Instituto de estudios ambientales - idea - manizales')], max_length=112, verbose_name='Faculty'),
        ),
    ]
