# Generated by Django 4.1 on 2022-08-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchers", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfessorModel",
            new_name="Professor",
        ),
        migrations.AlterModelOptions(
            name="professor",
            options={"verbose_name": "Professor"},
        ),
    ]
