# Generated by Django 4.1 on 2022-08-29 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("researchers", "0002_rename_professormodel_professor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Researcher",
            fields=[
                (
                    "personbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="researchers.personbase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Researcher",
            },
            bases=("researchers.personbase",),
        ),
    ]
