# Generated by Django 4.1 on 2022-08-29 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchers", "0003_researcher"),
    ]

    operations = [
        migrations.AddField(
            model_name="researcher",
            name="departed",
            field=models.DateField(blank=True, null=True, verbose_name="Departed"),
        ),
        migrations.AddField(
            model_name="researcher",
            name="joined",
            field=models.DateField(
                default=datetime.date(2022, 8, 29), verbose_name="Join"
            ),
        ),
    ]
