# Generated by Django 4.1 on 2022-08-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchers", "0004_researcher_departed_researcher_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researcher",
            name="joined",
            field=models.DateField(
                default="django.utils.timezone.now", verbose_name="Join"
            ),
        ),
    ]
