# Generated by Django 3.2.15 on 2022-12-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0004_auto_20221103_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Docente'},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'verbose_name': 'Investigador'},
        ),
        migrations.AlterField(
            model_name='professor',
            name='category',
            field=models.CharField(choices=[('researcher_category_0001', 'Investigador Asociado'), ('researcher_category_0002', 'Investigador Emérito'), ('researcher_category_0003', 'Investigador Junior'), ('researcher_category_0004', 'Investigador Senior'), ('researcher_category_0005', 'Sin información')], max_length=124, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='departament',
            field=models.CharField(choices=[('departament_0001', 'Departamento de Administración'), ('departament_0002', 'Departamento de Ciencias Humanas'), ('departament_0003', 'Departamento de Física y Química'), ('departament_0004', 'Departamento de Informática y Computación'), ('departament_0005', 'Departamento de Ingeniería Civil'), ('departament_0006', 'Departamento de Ingeniería Eléctrica, Electrónica y Computación'), ('departament_0007', 'Departamento de Ingeniería Industrial'), ('departament_0008', 'Departamento de Ingeniería Química'), ('departament_0009', 'Departamento de Matemáticas'), ('departament_0010', 'Escuela de Arquitectura y Urbanismo')], max_length=116, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='faculty',
            field=models.CharField(choices=[('faculty_0001', 'Facultad de Administración'), ('faculty_0002', 'Facultad de Ciencias Exactas y Naturales'), ('faculty_0003', 'Facultad de Ingeniería y Arquitectura')], max_length=112, verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Documento de identificación'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='departed',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de partida'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='joined',
            field=models.DateField(default='django.utils.timezone.now', verbose_name='Fecha de integración'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='researcher_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Documento de identificación'),
        ),
    ]
