# Generated by Django 4.1.2 on 2022-11-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1024, verbose_name='activity')),
                ('date', models.DateField(verbose_name='date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='finalization date')),
            ],
        ),
        migrations.CreateModel(
            name='JointCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/calls_internal', verbose_name='call')),
                ('expiration', models.DateField(verbose_name='expiration')),
                ('link', models.URLField(verbose_name='link')),
                ('title', models.CharField(max_length=1024, verbose_name='title')),
                ('objective', models.TextField(max_length=4096, verbose_name='objective')),
                ('headed', models.TextField(max_length=4096, verbose_name='headed')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='calls.timeline')),
            ],
        ),
    ]
