# Generated by Django 4.1.2 on 2022-11-08 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_timeline_jointcall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointcall',
            name='timeline',
        ),
        migrations.AddField(
            model_name='timeline',
            name='joint_call',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='calls.jointcall'),
            preserve_default=False,
        ),
    ]
