# Generated by Django 3.2.15 on 2022-11-10 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_annex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='date',
        ),
        migrations.AddField(
            model_name='timeline',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start_date'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TermsOfReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='name')),
                ('terms_of_reference', models.FileField(blank=True, null=True, upload_to='uploads/calls_internal', verbose_name='terms_of_reference')),
                ('joint_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='calls.jointcall')),
            ],
        ),
    ]
