# Generated by Django 3.2.15 on 2022-11-10 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_auto_20221110_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsofreference',
            name='joint_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_of_reference', to='calls.jointcall'),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='name')),
                ('results', models.FileField(blank=True, null=True, upload_to='uploads/calls_internal', verbose_name='results')),
                ('joint_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='calls.jointcall')),
            ],
        ),
    ]
