# Generated by Django 3.2.15 on 2022-11-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20221110_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointcall',
            name='expiration',
        ),
    ]
