# Generated by Django 3.2.15 on 2022-11-11 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_mincienciascall'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='title')),
                ('expiration', models.DateField(verbose_name='expiration')),
                ('funding', models.TextField(max_length=4096, verbose_name='funding')),
                ('supervise', models.TextField(max_length=4096, verbose_name='supervise')),
                ('students', models.IntegerField(verbose_name='students')),
                ('profile', models.TextField(max_length=4096, verbose_name='profile')),
                ('time', models.IntegerField(help_text='Horas a la semana', verbose_name='time')),
                ('economic_stimulus', models.TextField(max_length=4096, verbose_name='economic_stimulus')),
                ('period', models.IntegerField(help_text='Meses', verbose_name='period')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfReferenceS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='name')),
                ('terms_of_reference', models.FileField(blank=True, null=True, upload_to='uploads/calls_internal', verbose_name='terms_of_reference')),
                ('joint_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_of_reference', to='calls.studentscall')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='name')),
                ('results', models.FileField(blank=True, null=True, upload_to='uploads/calls_internal', verbose_name='results')),
                ('joint_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='calls.studentscall')),
            ],
        ),
        migrations.CreateModel(
            name='AnnexS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='name')),
                ('annex', models.FileField(blank=True, null=True, upload_to='uploads/calls_internal', verbose_name='annex')),
                ('joint_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annex', to='calls.studentscall')),
            ],
        ),
    ]
