# Generated by Django 4.1.2 on 2022-12-01 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0012_rename_resultss_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcall',
            name='headed',
            field=models.TextField(default='', max_length=4096, verbose_name='headed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jointcall',
            name='expiration',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='expiration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mincienciascall',
            name='headed',
            field=models.TextField(default='', max_length=4096, verbose_name='headed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mincienciascall',
            name='objective',
            field=models.TextField(default='', max_length=4096, verbose_name='objective'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentscall',
            name='economic_stimulus',
            field=models.CharField(max_length=4096, verbose_name='economic stimulus'),
        ),
        migrations.AlterField(
            model_name='studentscall',
            name='funding',
            field=models.CharField(max_length=4096, verbose_name='funding'),
        ),
        migrations.AlterField(
            model_name='studentscall',
            name='period',
            field=models.CharField(help_text='ej. 3 Meses y 5 días', max_length=1024, verbose_name='period'),
        ),
    ]
