# Generated by Django 3.2.15 on 2022-12-02 19:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0016_auto_20221202_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annex_studentscall',
            options={'verbose_name': 'Anexo'},
        ),
        migrations.AlterModelOptions(
            name='result_studentscall',
            options={'verbose_name': 'Resultado'},
        ),
        migrations.AlterModelOptions(
            name='studentscall',
            options={'verbose_name': 'Convocatoria para estudiantes auxiliares'},
        ),
        migrations.AlterModelOptions(
            name='termsofreference_studentscall',
            options={'verbose_name': 'Términos de referencia', 'verbose_name_plural': 'Términos de referencia'},
        ),
        migrations.AlterField(
            model_name='annex_studentscall',
            name='annex',
            field=models.FileField(blank=True, null=True, upload_to='uploads/calls_student', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='annex_studentscall',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='internalcall',
            name='expiration',
            field=models.DateField(help_text='Hasta cuando está abierta la convocatoria', verbose_name='Finalización'),
        ),
        migrations.AlterField(
            model_name='internalcall',
            name='headed',
            field=models.TextField(max_length=4096, verbose_name='Dirigido a'),
        ),
        migrations.AlterField(
            model_name='internalcall',
            name='image',
            field=models.FileField(blank=True, help_text='opcional', null=True, upload_to='uploads/calls_internal', verbose_name='Imagen de convocatoria'),
        ),
        migrations.AlterField(
            model_name='internalcall',
            name='link',
            field=models.URLField(verbose_name='Link de referencia'),
        ),
        migrations.AlterField(
            model_name='internalcall',
            name='objective',
            field=models.TextField(max_length=4096, verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='internalcall',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='mincienciascall',
            name='active',
            field=models.BooleanField(default=True, help_text='Oculta la convoctaria de la vista pública', verbose_name='Convocatoria activa'),
        ),
        migrations.AlterField(
            model_name='mincienciascall',
            name='objective',
            field=tinymce.models.HTMLField(max_length=4096, verbose_name='objective'),
        ),
        migrations.AlterField(
            model_name='result_studentscall',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='result_studentscall',
            name='results',
            field=models.FileField(blank=True, null=True, upload_to='uploads/calls_student', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='termsofreference_studentscall',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='termsofreference_studentscall',
            name='terms_of_reference',
            field=models.FileField(blank=True, null=True, upload_to='uploads/calls_student', verbose_name='Archivo'),
        ),
    ]
