# Generated by Django 3.2.15 on 2022-12-02 19:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0017_auto_20221202_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcall',
            name='active',
            field=tinymce.models.HTMLField(default=True, help_text='Oculta la convoctaria de la vista pública', verbose_name='Convocatoria activa'),
        ),
        migrations.AlterField(
            model_name='internalcall',
            name='headed',
            field=tinymce.models.HTMLField(max_length=4096, verbose_name='Dirigido a'),
        ),
    ]
