# Generated by Django 3.2.15 on 2022-12-02 20:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0019_auto_20221202_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annex_internalcall',
            options={'verbose_name': 'Anexo'},
        ),
        migrations.AlterModelOptions(
            name='annex_jointcall',
            options={'verbose_name': 'Anexo'},
        ),
        migrations.AlterModelOptions(
            name='internalcall',
            options={'verbose_name': 'Convocatoria interna', 'verbose_name_plural': 'Convocatorias internas'},
        ),
        migrations.AlterModelOptions(
            name='jointcall',
            options={'verbose_name': 'Convocatoria conjunta', 'verbose_name_plural': 'Convocatorias conjuntas'},
        ),
        migrations.AlterModelOptions(
            name='result_internalcall',
            options={'verbose_name': 'Resultado'},
        ),
        migrations.AlterModelOptions(
            name='studentscall',
            options={'verbose_name': 'Convocatoria para estudiantes auxiliares', 'verbose_name_plural': 'Convocatorias para estudiantes auxiliares'},
        ),
        migrations.AlterModelOptions(
            name='termsofreference_internalcall',
            options={'verbose_name': 'Términos de referencia', 'verbose_name_plural': 'Términos de referencia'},
        ),
        migrations.AlterModelOptions(
            name='termsofreference_jointcall',
            options={'verbose_name': 'Términos de referencia', 'verbose_name_plural': 'Términos de referencia'},
        ),
        migrations.AlterModelOptions(
            name='timeline_internalcall',
            options={'verbose_name': 'Cronograma', 'verbose_name_plural': 'Cronograma'},
        ),
        migrations.AlterModelOptions(
            name='timeline_jointcall',
            options={'verbose_name': 'Cronograma', 'verbose_name_plural': 'Cronograma'},
        ),
        migrations.AlterField(
            model_name='annex_internalcall',
            name='annex',
            field=models.FileField(blank=True, null=True, upload_to='uploads/calls_internal', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='annex_internalcall',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='annex_jointcall',
            name='annex',
            field=models.FileField(blank=True, null=True, upload_to='uploads/calls_student', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='annex_jointcall',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='internalcall',
            name='image',
            field=models.FileField(blank=True, help_text='Opcional', null=True, upload_to='uploads/calls_internal', verbose_name='Imagen de convocatoria'),
        ),
        migrations.AlterField(
            model_name='jointcall',
            name='active',
            field=models.BooleanField(default=True, help_text='Oculta la convoctaria de la vista pública', verbose_name='Convocatoria activa'),
        ),
        migrations.AlterField(
            model_name='jointcall',
            name='expiration',
            field=models.DateField(help_text='Hasta cuando está abierta la convocatoria', verbose_name='Finalización'),
        ),
        migrations.AlterField(
            model_name='jointcall',
            name='headed',
            field=tinymce.models.HTMLField(max_length=4096, verbose_name='Dirigido a'),
        ),
        migrations.AlterField(
            model_name='jointcall',
            name='image',
            field=models.FileField(blank=True, help_text='Opcional', null=True, upload_to='uploads/calls_join', verbose_name='Imagen de convocatoria'),
        ),
        migrations.AlterField(
            model_name='jointcall',
            name='link',
            field=models.URLField(verbose_name='Link de referencia'),
        ),
        migrations.AlterField(
            model_name='jointcall',
            name='objective',
            field=tinymce.models.HTMLField(max_length=4096, verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='jointcall',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='result_internalcall',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='result_internalcall',
            name='results',
            field=models.FileField(blank=True, null=True, upload_to='uploads/calls_internal', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='termsofreference_internalcall',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='termsofreference_internalcall',
            name='terms_of_reference',
            field=models.FileField(blank=True, null=True, upload_to='uploads/calls_internal', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='termsofreference_jointcall',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='termsofreference_jointcall',
            name='terms_of_reference',
            field=models.FileField(blank=True, null=True, upload_to='uploads/calls_student', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='timeline_internalcall',
            name='activity',
            field=models.CharField(max_length=1024, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='timeline_internalcall',
            name='end_date',
            field=models.DateField(blank=True, help_text='Opcional', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='timeline_internalcall',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='timeline_jointcall',
            name='activity',
            field=models.CharField(max_length=1024, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='timeline_jointcall',
            name='end_date',
            field=models.DateField(blank=True, help_text='Opcional', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='timeline_jointcall',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
