# Generated by Django 3.2.15 on 2022-12-02 20:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0020_auto_20221202_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mincienciascall',
            options={'verbose_name': 'Convocatoria de Minciencias', 'verbose_name_plural': 'Convocatorias de Minciencias'},
        ),
        migrations.AlterField(
            model_name='mincienciascall',
            name='expiration',
            field=models.DateField(help_text='Hasta cuando está abierta la convocatoria', verbose_name='Finalización'),
        ),
        migrations.AlterField(
            model_name='mincienciascall',
            name='headed',
            field=tinymce.models.HTMLField(max_length=4096, verbose_name='Dirigido a'),
        ),
        migrations.AlterField(
            model_name='mincienciascall',
            name='image',
            field=models.FileField(blank=True, help_text='Opcional', null=True, upload_to='uploads/calls_internal', verbose_name='Imagen de convocatoria'),
        ),
        migrations.AlterField(
            model_name='mincienciascall',
            name='link',
            field=models.URLField(verbose_name='Link de referencia'),
        ),
        migrations.AlterField(
            model_name='mincienciascall',
            name='objective',
            field=tinymce.models.HTMLField(max_length=4096, verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='mincienciascall',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Título'),
        ),
    ]
