# Generated by Django 3.2.15 on 2022-08-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('pr', 'Professor'), ('st', 'Student')], max_length=2)),
            ],
        ),
    ]
