# Generated by Django 3.2.15 on 2022-08-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('faculty', models.CharField(max_length=64)),
                ('departament', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B', 'B'), ('C', 'C'), ('NA', 'No reconcido')], max_length=2)),
                ('sub_ocde', models.CharField(choices=[], max_length=2)),
                ('ocde', models.CharField(choices=[], max_length=2)),
                ('knowledge', models.CharField(choices=[], max_length=2)),
                ('leader', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='research_groups.researcher')),
                ('researchers', models.ManyToManyField(related_name='researchers', to='research_groups.Researcher')),
            ],
        ),
    ]
