# Generated by Django 3.2.15 on 2022-08-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_groups', '0003_auto_20220811_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='knowledge',
            field=models.CharField(choices=[('amb', 'Ambiente y biodiversidad'), ('art', 'Arte y culturas'), ('bio', 'Biotecnología'), ('tec', 'Ciencia y tecnología de minerales y materiales'), ('agr', 'Ciencias agrarias y desarrollo rural'), ('ciu', 'Construcción de ciudadanía e inclusión social'), ('des', 'Desarrollo organizacional, económico e industrial'), ('ene', 'Energía'), ('est', 'Estados, sistemas políticos y jurídicos'), ('hab', 'Hábitat, ciudad y territorio'), ('sal', 'Salud y vida'), ('tic', 'Tecnologías de la información y las comunicaciones (TIC)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='ocde',
            field=models.CharField(choices=[('nat', 'Ciencias naturales'), ('ing', 'Ingeniería y tecnología'), ('med', 'Ciencias médicas y de la salud'), ('agr', 'Ciencias agrícolas'), ('soc', 'Ciencias sociales'), ('hum', 'Humanidades')], max_length=3),
        ),
    ]
