# Generated by Django 3.2.15 on 2022-08-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_groups', '0004_auto_20220811_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='sub_ocde',
            field=models.CharField(choices=[('aaa', 'bbb')], max_length=3),
        ),
    ]
