# Generated by Django 3.2.15 on 2022-08-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_groups', '0005_alter_researchgroup_sub_ocde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='role',
        ),
    ]
