# Generated by Django 3.2.15 on 2022-08-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_groups', '0006_remove_researcher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='category',
            field=models.CharField(choices=[('cat_00', 'A1'), ('cat_01', 'A2'), ('cat_02', 'B'), ('cat_03', 'C'), ('cat_04', 'No reconcido')], max_length=6),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='departament',
            field=models.CharField(choices=[('dep_00', 'Departamento de administración'), ('dep_01', 'Departamento de ciencias humanas'), ('dep_02', 'Departamento de física y química'), ('dep_03', 'Departamento de informática y computación'), ('dep_04', 'Departamento de ingeniería civil'), ('dep_05', 'Departamento de ingeniería eléctrica, electrónica y computación'), ('dep_06', 'Departamento de ingeniería industrial'), ('dep_07', 'Departamento de ingeniería química'), ('dep_08', 'Departamento de matemáticas'), ('dep_09', 'Escuela de arquitectura y urbanismo')], max_length=6),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='faculty',
            field=models.CharField(choices=[('fac_00', 'Facultad de administración'), ('fac_01', 'Facultad de ciencias excatas y naturales'), ('fac_02', 'Facultad de ingeniería y arquitectura')], max_length=6),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='knowledge',
            field=models.CharField(choices=[('area_00', 'Ambiente y biodiversidad'), ('area_01', 'Arte y culturas'), ('area_02', 'Biotecnología'), ('area_03', 'Ciencia y tecnología de minerales y materiales'), ('area_04', 'Ciencias agrarias y desarrollo rural'), ('area_05', 'Construcción de ciudadanía e inclusión social'), ('area_06', 'Desarrollo organizacional, económico e industrial'), ('area_07', 'Energía'), ('area_08', 'Estados, sistemas políticos y jurídicos'), ('area_09', 'Hábitat, ciudad y territorio'), ('area_10', 'Salud y vida'), ('area_11', 'Tecnologías de la información y las comunicaciones (TIC)')], max_length=7),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='ocde',
            field=models.CharField(choices=[('ocde_00', 'Ciencias agrícolas'), ('ocde_01', 'Ciencias médicas y de la salud'), ('ocde_02', 'Ciencias naturales'), ('ocde_03', 'Ciencias sociales'), ('ocde_04', 'Humanidades'), ('ocde_05', 'Ingeniería y tecnología')], max_length=7),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='sub_ocde',
            field=models.CharField(choices=[('sub_ocde_00', 'bbb')], max_length=11),
        ),
    ]
