# Generated by Django 3.2.15 on 2022-08-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_groups', '0009_alter_researchgroup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='faculty',
            field=models.CharField(choices=[('fac_01', 'Facultad de administración'), ('fac_02', 'Facultad de ciencias exactas y naturales'), ('fac_03', 'Facultad de ingeniería y arquitectura')], max_length=6),
        ),
    ]
