# Generated by Django 3.2.15 on 2022-10-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/broadcast', verbose_name='broadcast')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('dominant', models.CharField(blank=True, max_length=7, null=True, verbose_name='dominant')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='description')),
                ('upload', models.DateTimeField(auto_now_add=True, verbose_name='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/newsletter', verbose_name='newsletter')),
                ('upload', models.DateTimeField(auto_now_add=True, verbose_name='upload')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/newsletter', verbose_name='thumbnail')),
            ],
        ),
    ]
