# Generated by Django 3.2.15 on 2022-10-07 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='expiration',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='expiration'),
            preserve_default=False,
        ),
    ]
