# Generated by Django 3.2.15 on 2022-09-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='file',
            field=models.FileField(upload_to='media_root/uploads', verbose_name='newsletter'),
        ),
    ]
