# Generated by Django 3.2.15 on 2022-09-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0002_alter_newsletter_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='file',
            field=models.FileField(upload_to='media_root/uploads/newsletter', verbose_name='newsletter'),
        ),
    ]
