# Generated by Django 3.2.15 on 2022-11-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0002_alter_team_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
            preserve_default=False,
        ),
    ]
