# Generated by Django 3.2.15 on 2022-10-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0002_broadcast_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=256, verbose_name='area')),
                ('names', models.CharField(max_length=256, verbose_name='names (separated by comma)')),
                ('email', models.CharField(max_length=256, verbose_name='emails (separated by comma)')),
                ('ext', models.CharField(max_length=256, verbose_name='extention (separated by comma)')),
            ],
        ),
    ]
