# Generated by Django 3.2.15 on 2022-10-15 00:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('label', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='label')),
                ('content', tinymce.models.HTMLField(max_length=32768, verbose_name='content')),
            ],
        ),
    ]
