# Generated by Django 3.2.15 on 2022-10-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('label', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='label')),
                ('content', models.TextField(max_length=32768, verbose_name='content')),
            ],
        ),
    ]
