# Generated by Django 3.2.15 on 2022-09-29 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0003_alter_newsletter_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='upload'),
            preserve_default=False,
        ),
    ]
