# Generated by Django 4.1.2 on 2022-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0003_broadcast_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/calls_internal', verbose_name='call')),
                ('expiration', models.DateField(verbose_name='expiration')),
                ('link', models.URLField(verbose_name='link')),
                ('title', models.CharField(max_length=1024, verbose_name='title')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
