# Generated by Django 3.2.15 on 2022-10-13 19:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0004_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=32768, verbose_name='content'),
        ),
    ]
