# Generated by Django 3.2.15 on 2022-09-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0004_newsletter_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media_root/uploads/newsletter', verbose_name='thumbnail'),
        ),
    ]
