# Generated by Django 4.1.2 on 2022-11-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0004_internalcall_alter_broadcast_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalCall',
        ),
    ]
