# Generated by Django 3.2.15 on 2022-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0005_newsletter_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='file',
            field=models.FileField(upload_to='uploads/newsletter', verbose_name='newsletter'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/newsletter', verbose_name='thumbnail'),
        ),
    ]
