# Generated by Django 3.2.15 on 2022-10-13 19:43

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0005_alter_content_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=django_quill.fields.QuillField(max_length=32768, verbose_name='content'),
        ),
    ]
