# Generated by Django 3.2.15 on 2022-09-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0006_auto_20220929_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/broadcast', verbose_name='broadcast')),
                ('link', models.URLField(blank=True, null=True, verbose_name='broadcast')),
                ('dominant', models.CharField(blank=True, max_length=7, null=True, verbose_name='dominant')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='description')),
            ],
        ),
    ]
