# Generated by Django 3.2.15 on 2022-12-05 23:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0006_auto_20221110_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={'verbose_name': 'Difusión (imagen en carusel)', 'verbose_name_plural': 'Difusiónes'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Contenido estático', 'verbose_name_plural': 'Contenidos estáticos'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Boletín', 'verbose_name_plural': 'Boletines'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Equipo de trabajo', 'verbose_name_plural': 'Equipo de trabajo'},
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='active',
            field=models.BooleanField(default=True, help_text='La oculta del carusel ', verbose_name='Difusión activa'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='description',
            field=models.TextField(blank=True, help_text='Opcional', max_length=1024, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='dominant',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='expiration',
            field=models.DateField(help_text='Hasta cuando será visible en el carusel', verbose_name='Finalización'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='image',
            field=models.FileField(upload_to='uploads/broadcast', verbose_name='Imagen para difusión'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='link',
            field=models.URLField(blank=True, help_text='Opcional', null=True, verbose_name='Link de referencia'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='title',
            field=models.CharField(blank=True, help_text='Opcional', max_length=1024, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=tinymce.models.HTMLField(max_length=32768, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='content',
            name='label',
            field=models.CharField(editable=False, max_length=128, primary_key=True, serialize=False, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='file',
            field=models.FileField(upload_to='uploads/newsletter', verbose_name='Boletín'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/newsletter'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='area',
            field=models.CharField(max_length=256, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.CharField(help_text='Separados por coma (,)', max_length=256, verbose_name='Correos electrónicos'),
        ),
        migrations.AlterField(
            model_name='team',
            name='ext',
            field=models.CharField(help_text='Separados por coma (,)', max_length=8, verbose_name='Extensiones'),
        ),
        migrations.AlterField(
            model_name='team',
            name='names',
            field=models.CharField(help_text='Separados por coma (,)', max_length=256, verbose_name='Nombres'),
        ),
    ]
