# Generated by Django 3.2.15 on 2022-10-14 02:46

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0006_alter_content_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=django_editorjs.fields.EditorJsField(max_length=32768),
        ),
    ]
