# Generated by Django 3.2.15 on 2022-10-14 03:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0007_alter_content_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=tinymce.models.HTMLField(max_length=32768, verbose_name='content'),
        ),
    ]
