# Generated by Django 3.2.15 on 2022-09-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0008_broadcast_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='title',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
    ]
