# Generated by Django 3.2.15 on 2022-09-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0009_auto_20220930_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='title'),
        ),
    ]
