# Generated by Django 4.1.2 on 2022-10-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='researchers',
            field=models.TextField(blank=True, max_length=65536, null=True, verbose_name='Researchers'),
        ),
    ]
