# Generated by Django 3.2.15 on 2022-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='category',
            field=models.CharField(choices=[('groups_category_0001', 'A'), ('groups_category_0002', 'A1'), ('groups_category_0003', 'B'), ('groups_category_0004', 'C'), ('groups_category_0005', 'No reconocido')], max_length=120, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='departament',
            field=models.CharField(choices=[('departament_0001', 'Departamento de administración'), ('departament_0002', 'Departamento de ciencias humanas'), ('departament_0003', 'Departamento de física y química'), ('departament_0004', 'Departamento de informática y computación'), ('departament_0005', 'Departamento de ingeniería civil'), ('departament_0006', 'Departamento de ingeniería eléctrica, electrónica y computación'), ('departament_0007', 'Departamento de ingeniería industrial'), ('departament_0008', 'Departamento de ingeniería química'), ('departament_0009', 'Departamento de matemáticas'), ('departament_0010', 'Escuela de arquitectura y urbanismo'), ('departament_0011', 'Instituto de estudios ambientales - idea - manizales')], max_length=116, verbose_name='Departament'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='faculty',
            field=models.CharField(choices=[('faculty_0001', 'Facultad de administración'), ('faculty_0002', 'Facultad de ciencias exactas y naturales'), ('faculty_0003', 'Facultad de ingeniería y arquitectura'), ('faculty_0004', 'Instituto de estudios ambientales - idea - manizales')], max_length=112, verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='knowledge_area',
            field=models.CharField(choices=[('knowledge_0001', 'Ambiente y biodiversidad'), ('knowledge_0002', 'Arte y cultura'), ('knowledge_0003', 'Biotecnología'), ('knowledge_0004', 'Ciencia y tecnología de minerales y materiales'), ('knowledge_0005', 'Ciencias agrarias y desarrollo rural'), ('knowledge_0006', 'Construcción de ciudadanía e inclusión social'), ('knowledge_0007', 'Desarrollo organizacional, económico e industrial'), ('knowledge_0008', 'Energía'), ('knowledge_0009', 'Estados, sistemas políticos y jurídicos'), ('knowledge_0010', 'Hábitat, ciudad y territorio'), ('knowledge_0011', 'Salud y vida'), ('knowledge_0012', 'Tecnologías de la información y las comunicaciones')], max_length=114, verbose_name='Knowledge area'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='ocde',
            field=models.CharField(choices=[('ocde_0001', 'Agricultura, silvicultura y pesca'), ('ocde_0002', 'Arte'), ('ocde_0003', 'Biotecnología agrícola'), ('ocde_0004', 'Biotecnología ambiental'), ('ocde_0005', 'Biotecnología en salud'), ('ocde_0006', 'Biotecnología industrial'), ('ocde_0007', 'Ciencias animales y lechería'), ('ocde_0008', 'Ciencias biológicas'), ('ocde_0009', 'Ciencias de la educación'), ('ocde_0010', 'Ciencias de la salud'), ('ocde_0011', 'Ciencias de la tierra y medioambientales'), ('ocde_0012', 'Ciencias físicas'), ('ocde_0013', 'Ciencias políticas'), ('ocde_0014', 'Ciencias químicas'), ('ocde_0015', 'Ciencias veterinarias'), ('ocde_0016', 'Computación y ciencias de la información'), ('ocde_0017', 'Derecho'), ('ocde_0018', 'Economía y negocios'), ('ocde_0019', 'Geografía social y económica'), ('ocde_0020', 'Historia y arqueología'), ('ocde_0021', 'Idiomas y literatura'), ('ocde_0022', 'Ingeniería ambiental'), ('ocde_0023', 'Ingeniería civil'), ('ocde_0024', 'Ingeniería de materiales'), ('ocde_0025', 'Ingeniería mecánica'), ('ocde_0026', 'Ingeniería médica'), ('ocde_0027', 'Ingeniería química'), ('ocde_0028', 'Ingenierías eléctrica, electrónica e informática'), ('ocde_0029', 'Matemática'), ('ocde_0030', 'Medicina básica'), ('ocde_0031', 'Medicina clínica'), ('ocde_0032', 'Nanotecnología'), ('ocde_0033', 'Otras ciencias agrícolas'), ('ocde_0034', 'Otras ciencias médicas'), ('ocde_0035', 'Otras ciencias naturales'), ('ocde_0036', 'Otras ciencias sociales'), ('ocde_0037', 'Otras historias'), ('ocde_0038', 'Otras humanidades'), ('ocde_0039', 'Otras ingenierías tecnologías'), ('ocde_0040', 'Periodismo y comunicaciones'), ('ocde_0041', 'Psicología'), ('ocde_0042', 'Sociología')], max_length=109, verbose_name='OCDE'),
        ),
    ]
