# Generated by Django 3.2.15 on 2022-09-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='knowledge_area',
            field=models.CharField(choices=[('knowledge_0001', 'Ambiente y biodiversidad'), ('knowledge_0002', 'Arte y cultura'), ('knowledge_0003', 'Biotecnología'), ('knowledge_0004', 'Ciencia y tecnología de minerales y materiales'), ('knowledge_0005', 'Ciencias agrarias y desarrollo rural'), ('knowledge_0006', 'Construcción de ciudadanía e inclusión social'), ('knowledge_0007', 'Desarrollo organizacional, económico e industrial'), ('knowledge_0008', 'Energía'), ('knowledge_0009', 'Estados, sistemas políticos y jurídicos'), ('knowledge_0010', 'Hábitat, ciudad y territorio'), ('knowledge_0011', 'Salud y vida'), ('knowledge_0012', 'Tecnologías de la información y las comunicaciones')], max_length=14, verbose_name='Knowledge area'),
        ),
    ]
