# Generated by Django 4.1 on 2022-08-29 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchgroup",
            name="founded",
            field=models.DateField(
                default=datetime.date(2022, 8, 29), verbose_name="Founded"
            ),
        ),
    ]
