# Generated by Django 4.1 on 2022-08-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchers", "0004_researcher_departed_researcher_joined"),
        ("groups", "0002_researchgroup_founded"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchgroup",
            name="researchers",
            field=models.ManyToManyField(
                related_name="researchers", to="researchers.researcher"
            ),
        ),
    ]
