# Generated by Django 3.2.15 on 2022-10-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_researchgroup_ocde'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchgroup',
            name='gruplac',
            field=models.URLField(blank=True, null=True, verbose_name='GrupLAC'),
        ),
    ]
