# Generated by Django 3.2.15 on 2022-10-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_researchgroup_gruplac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchgroup',
            name='researchers',
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='researchers',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Researchers'),
        ),
    ]
