# Generated by Django 3.2.15 on 2022-11-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20221103_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='departament',
            field=models.CharField(choices=[('departament_0001', 'Departamento de Administración'), ('departament_0002', 'Departamento de Ciencias Humanas'), ('departament_0003', 'Departamento de Física y Química'), ('departament_0004', 'Departamento de Informática y Computación'), ('departament_0005', 'Departamento de Ingeniería Civil'), ('departament_0006', 'Departamento de Ingeniería Eléctrica, Electrónica y Computación'), ('departament_0007', 'Departamento de Ingeniería Industrial'), ('departament_0008', 'Departamento de Ingeniería Química'), ('departament_0009', 'Departamento de Matemáticas'), ('departament_0010', 'Escuela de Arquitectura y Urbanismo')], max_length=116, verbose_name='Departament'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='faculty',
            field=models.CharField(choices=[('faculty_0001', 'Facultad de Administración'), ('faculty_0002', 'Facultad de Ciencias Exactas y Naturales'), ('faculty_0003', 'Facultad de Ingeniería y Arquitectura')], max_length=112, verbose_name='Faculty'),
        ),
    ]
