# Generated by Django 3.2.15 on 2022-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20221016_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='researchers',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Researchers'),
        ),
    ]
