# Generated by Django 3.2.15 on 2022-12-05 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0005_auto_20221205_1847'),
        ('groups', '0005_auto_20221103_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchgroup',
            options={'verbose_name': 'Grupo de investigación', 'verbose_name_plural': 'Grupos de investigación'},
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='category',
            field=models.CharField(choices=[('groups_category_0001', 'A'), ('groups_category_0002', 'A1'), ('groups_category_0003', 'B'), ('groups_category_0004', 'C'), ('groups_category_0005', 'No reconocido')], max_length=120, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='departament',
            field=models.CharField(choices=[('departament_0001', 'Departamento de Administración'), ('departament_0002', 'Departamento de Ciencias Humanas'), ('departament_0003', 'Departamento de Física y Química'), ('departament_0004', 'Departamento de Informática y Computación'), ('departament_0005', 'Departamento de Ingeniería Civil'), ('departament_0006', 'Departamento de Ingeniería Eléctrica, Electrónica y Computación'), ('departament_0007', 'Departamento de Ingeniería Industrial'), ('departament_0008', 'Departamento de Ingeniería Química'), ('departament_0009', 'Departamento de Matemáticas'), ('departament_0010', 'Escuela de Arquitectura y Urbanismo')], max_length=116, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='faculty',
            field=models.CharField(choices=[('faculty_0001', 'Facultad de Administración'), ('faculty_0002', 'Facultad de Ciencias Exactas y Naturales'), ('faculty_0003', 'Facultad de Ingeniería y Arquitectura')], max_length=112, verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='founded',
            field=models.DateField(default='django.utils.timezone.now', verbose_name='Fecha de fundación'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='hermes_code',
            field=models.CharField(max_length=32, verbose_name='Código Hermes'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='knowledge_area',
            field=models.CharField(choices=[('knowledge_0001', 'Ambiente y biodiversidad'), ('knowledge_0002', 'Arte y cultura'), ('knowledge_0003', 'Biotecnología'), ('knowledge_0004', 'Ciencia y tecnología de minerales y materiales'), ('knowledge_0005', 'Ciencias agrarias y desarrollo rural'), ('knowledge_0006', 'Construcción de ciudadanía e inclusión social'), ('knowledge_0007', 'Desarrollo organizacional, económico e industrial'), ('knowledge_0008', 'Energía'), ('knowledge_0009', 'Estados, sistemas políticos y jurídicos'), ('knowledge_0010', 'Hábitat, ciudad y territorio'), ('knowledge_0011', 'Salud y vida'), ('knowledge_0012', 'Tecnologías de la información y las comunicaciones')], max_length=114, verbose_name='Área del conocimiento'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='researchers.professor', verbose_name='Lider'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='minciencias_code',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Código Minciencias'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nombre del grupo'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='research',
            field=models.CharField(max_length=1024, verbose_name='Lineas de investigación'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='researchers',
            field=models.TextField(blank=True, max_length=65536, null=True, verbose_name='Investigadores'),
        ),
    ]
