# Generated by Django 3.2.15 on 2022-10-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
        ('groups', '0005_alter_researchgroup_researchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='researchers.professor'),
        ),
    ]
