# Generated by Django 4.1.2 on 2022-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('filed', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Filed')),
                ('co_ownership', models.CharField(max_length=1024, verbose_name='Co-ownership')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('patent_type', models.CharField(choices=[('patent_type_0001', 'Patente de invención'), ('patent_type_0002', 'Patente modelo de utilidad')], max_length=116, verbose_name='Patent type')),
                ('departament', models.CharField(choices=[('departament_0001', 'Departamento de administración'), ('departament_0002', 'Departamento de ciencias humanas'), ('departament_0003', 'Departamento de física y química'), ('departament_0004', 'Departamento de informática y computación'), ('departament_0005', 'Departamento de ingeniería civil'), ('departament_0006', 'Departamento de ingeniería eléctrica, electrónica y computación'), ('departament_0007', 'Departamento de ingeniería industrial'), ('departament_0008', 'Departamento de ingeniería química'), ('departament_0009', 'Departamento de matemáticas'), ('departament_0010', 'Escuela de arquitectura y urbanismo'), ('departament_0011', 'Instituto de estudios ambientales - idea - manizales')], max_length=116, verbose_name='Departament')),
                ('grant', models.DateField(default='django.utils.timezone.now', verbose_name='Grant')),
                ('filing', models.DateField(default='django.utils.timezone.now', verbose_name='Filing')),
                ('publication', models.DateField(default='django.utils.timezone.now', verbose_name='Publication')),
                ('inventors', models.ManyToManyField(to='researchers.professor')),
            ],
        ),
    ]
