# Generated by Django 3.2.15 on 2022-09-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0002_auto_20220915_1817'),
        ('intellectual_property', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patents',
            new_name='Patent',
        ),
    ]
