# Generated by Django 4.1.2 on 2022-10-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
        ('intellectual_property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patent',
            old_name='filing',
            new_name='filling',
        ),
        migrations.AlterField(
            model_name='patent',
            name='inventors',
            field=models.ManyToManyField(related_name='patents', to='researchers.professor'),
        ),
    ]
