# Generated by Django 3.2.15 on 2022-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellectual_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='departament',
            field=models.CharField(choices=[('departament_0001', 'Departamento de administración'), ('departament_0002', 'Departamento de ciencias humanas'), ('departament_0003', 'Departamento de física y química'), ('departament_0004', 'Departamento de informática y computación'), ('departament_0005', 'Departamento de ingeniería civil'), ('departament_0006', 'Departamento de ingeniería eléctrica, electrónica y computación'), ('departament_0007', 'Departamento de ingeniería industrial'), ('departament_0008', 'Departamento de ingeniería química'), ('departament_0009', 'Departamento de matemáticas'), ('departament_0010', 'Escuela de arquitectura y urbanismo'), ('departament_0011', 'Instituto de estudios ambientales - idea - manizales')], max_length=116, verbose_name='Departament'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_type',
            field=models.CharField(choices=[('patent_type_0001', 'Patente de invención'), ('patent_type_0002', 'Patente modelo de utilidad')], max_length=116, verbose_name='Patent type'),
        ),
    ]
