# Generated by Django 3.2.15 on 2022-11-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellectual_property', '0003_alter_patent_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='departament',
            field=models.CharField(choices=[('departament_0001', 'Departamento de Administración'), ('departament_0002', 'Departamento de Ciencias Humanas'), ('departament_0003', 'Departamento de Física y Química'), ('departament_0004', 'Departamento de Informática y Computación'), ('departament_0005', 'Departamento de Ingeniería Civil'), ('departament_0006', 'Departamento de Ingeniería Eléctrica, Electrónica y Computación'), ('departament_0007', 'Departamento de Ingeniería Industrial'), ('departament_0008', 'Departamento de Ingeniería Química'), ('departament_0009', 'Departamento de Matemáticas'), ('departament_0010', 'Escuela de Arquitectura y Urbanismo')], max_length=116, verbose_name='Departament'),
        ),
    ]
